### ISSUE TITLE
前辈，可不可以请教一下你，学习这本书的历程与经验

### ISSUE THREAD

**Issue by ZhangQianZhe** [hacheyz/PMMAA#1]

**Comment by hacheyz** [comment]
看这本书最重要的是动手。
不知道你打什么位置，如果是编程手的话，可以试着把书里的代码手打然后跑一遍。每章后面的练习题先自己做，想不出来再看答案。如果你没有科学计算的基础，这个过程非常重要，因为它可以帮你锻炼使用编程工具和构思代码的能力。
除了一些比较常用的函数之外，别的函数没必要特意记它的用法，一方面很容易忘，另一方面 IDE 的提示已经做的很好了，比如 VSCode 早已集成了文档功能，可以现用现查。
最后，如果你是编程手，我认为书里的一些复杂的数学推导你大可略过不看。因为编程手关注的是如何快速实现一个已经描述好的算法，而不是自行推导算法。此外，比赛的时候很可能都用不到书上的知识，但由于打下了良好的基础，便能快速地掌握一种新算法，我觉得这才是这本书的意义所在。

**Comment by ZhangQianZhe** [comment]
好的，谢谢！我在看您的代码时，发现您写的代码结构很清晰，语句用的也很灵活，收获很多
