### ISSUE TITLE
发现一点小错误

### ISSUE THREAD

**Issue by Murnomous24** [hacheyz/PMMAA#2]
02 Python 使用入门-2.4 numpy.ipynb-22 中矩阵乘法有误，应该是 `b@a`。
非常感谢作者，才入门数模，想咨询一个问题，作为编程手，应该去练习什么提高自己对已有数据的处理能力和获取与比赛有关数据的能力？

**Comment by hacheyz** [comment]
[相关代码](https://github.com/hacheyz/PMMAA/blob/main/02%20Python%20%E4%BD%BF%E7%94%A8%E5%85%A5%E9%97%A8/2.4%20numpy.ipynb)

感谢捉虫😊但是如果我没记错的话，这个 bug 是我故意设置的，为的是演示使用 `@` 运算符执行矩阵乘法的要求（这也是矩阵乘法运算的基本要求），这样日后看到类似的报错，就知道是矩阵维数对不上导致的。这里我没有对自己的用意进行一个说明，非常抱歉给你带来了困扰。

关于如何提高数据处理能力，你可以尝试自己做或者跟着教程做几个机器学习的小项目，因为机器学习往往设计到对数据的预处理和组织，实践过后能学到许多管理数据的函数，遇到报错并解决也能降低你实战时程序出错的概率，从而增强你对数据的掌控力。

关于如何获取与比赛相关的数据，如果你说的数据是能够直接参与计算的那种数据，以我参加国赛的经历来看，并没有必要去搜集这些数据，因为题目所给的数据已经足够。美赛不太了解，如果要找数据集的话可以去 [Kaggle ](https://www.kaggle.com/)看看。

**Comment by Murnomous24** [comment]
Thx!😉
